Petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('pets/', include('pets.urls')),
    path('photos/', include('photos.urls')),
]

accounts/urls.py
from django.urls import path, include

from accounts import views

app_name = 'accounts'

profile_patterns = [
    path('', views.profile_details, name='details'),
    path('edit/', views.profile_edit, name='edit'),
    path('delete/', views.profile_delete, name='delete'),
]

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('profile/<int:pk>/', include(profile_patterns)),
]

common/urls.py
from django.urls import path

from common import views


app_name = 'common'

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

pets/urls.py
from django.urls import path, include

from pets import views

app_name = 'pets'

pets_patter = [
    path('', views.pet_details, name='pet_details'),
    path('edit/', views.pet_edit, name='pet-details'),
    path('delete/', views.pet_delete, name='pet-delete')
]

urlpatterns = [
    path('', views.pet_add, name='pet-add'),
    path('<str:username>/pet/<slug:pet_slug>/', include(pets_patter)),

]

photos/urls.py
from django.urls import path, include

from photos import views

app_name = 'photos'

photo_patterns = [
    path('', views.detail_photo, name='detail-photo'),
    path('edit/', views.edit_photo, name='edit-photo'),
]

urlpatterns = [
    path('add/', views.add_photo, name='add-photo'),
    path('<int:pk>', include(photo_patterns)),
]

accounts/models.py
from django.db import models

# Create your models here.

common/models.py
from django.db import models

from photos.models import Photo


class Comment(models.Model):
    text = models.CharField(max_length=300)
    date_and_time_of_publication = models.DateTimeField(auto_now_add=True)
    to_photo = models.ForeignKey("photos.Photo", on_delete=models.CASCADE)

class Like(models.Model):
    to_photo = models.ForeignKey("photos.Photo", on_delete=models.CASCADE)

pets/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Pet(models.Model):
    name = models.CharField(max_length=30)
    personal_photo = models.URLField()
    date_of_birth = models.DateField(blank=True, null=True)
    slug = models.SlugField(unique=True, null=False, blank=True, editable=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.name}-{self.pk}")
        super().save(*args, **kwargs)

photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from photos.validators import FileSizeValidator


class Photo(models.Model):
    photo = models.ImageField(validators=[FileSizeValidator(5)])
    description = models.CharField(max_length=100, validators=[MinLengthValidator(10)], null=True, blank=True)
    locations = models.CharField(max_length=30)
    tagged_pets = models.ManyToManyField(to='pets.Pet', blank=True, null=True)
    date_of_published = models.DateField(auto_now=True)

    def __str__(self):
        return self.photo.name

accounts/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

def register(request: HttpRequest) -> HttpResponse:
    return render(request, 'accounts/register-page.html')

def login(request: HttpRequest) -> HttpResponse:
    return render(request, 'accounts/login-page.html')

def profile_details(request: HttpRequest) -> HttpResponse:
    return render(request, 'accounts/profile-details-page.html')

def profile_edit(request: HttpRequest) -> HttpResponse:
    return render(request, 'accounts/profile-edit-page.html')

def profile_delete(request: HttpRequest) -> HttpResponse:
    return render(request, 'accounts/profile-delete-page.html')

common/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


def home_page(request: HttpRequest) -> HttpResponse:
    return render(request, 'common/home-page.html')

pets/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


def pet_add(request: HttpRequest) -> HttpResponse:
    return render(request, 'pets/pet-add-page.html')

def pet_details(request: HttpRequest) -> HttpResponse:
    return render(request, 'pets/pet-details-page.html')

def pet_edit(request: HttpRequest) -> HttpResponse:
    return render(request, 'pets/pet-edit-page.html')

def pet_delete(request: HttpRequest) -> HttpResponse:
    return render(request, 'pets/pet-delete-page.html')

photos/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


def add_photo(request: HttpRequest) -> HttpResponse:
    return render(request, 'photos/photo-add-page.html')

def detail_photo(request: HttpRequest) -> HttpResponse:
    return render(request, 'photos/photo-details-page.html')

def edit_photo(request: HttpRequest) -> HttpResponse:
    return render(request, 'photos/photo-edit-page.html')

templates/accounts/login-page.html
{% extends 'shared/base.html' %}

{% block content %}
    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form action="#">
                <p>
                    <label for="id_username">Username:</label>
                    <input type="text" placeholder="Username">
                </p>
                <p>
                    <label for="id_password">Password:</label>
                    <input type="password" placeholder="Password">
                </p>

                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have an account? <a href="#">Register</a></p>
        </div>
    </div>
{% endblock %}
    <!-- End Login Section-->

templates/accounts/profile-delete-page.html
{% extends 'shared/base.html' %}

{% block content %}

    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="/static/images/are_you_sure_cat.gif" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->

{% endblock %}

templates/accounts/profile-details-page.html
{% extends 'shared/base.html' %}

{% block content %}

      <!-- Start Profile Details Section -->
      <div class="profile">
        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
          <div class="profile_img">
            <div class="image">
              <!-- Profile Image -->
              <img src="/static/images/person.png" alt="img8" />
            </div>
          </div>
          <div class="personal">
            <div class="edit">
              <!-- User Username -->
              <p>d_kalaydzhiev</p>

              <!-- IF the viewer is the owner of the profile -->
              <!-- Link to Edit Profile Page -->
              <a href="#">
                <img
                  class="edit-img"
                  src="/static/images/edit-pen-icon-6.jpg"
                  alt="edit button"
                />
              </a>

              <!-- Link to Delete Profile Page -->
              <a href="">
                <img
                  class="bin-img"
                  src="/static/images/icon-remove-22.jpg"
                  alt="bin button"
                />
              </a>
              <!-- End IF the viewer is the owner of the profile -->
            </div>
            <div class="data">
              <!-- Total Number of Photos by the User -->
              <span>4</span>
              <p>photos</p>

              <!-- Total Number of Pets owned by the User -->
              <span>7</span>
              <p>pets</p>

              <!-- Total Number of Likes for the User -->
              <span>436</span>
              <p>likes</p>
            </div>
            <!-- User First and Last Name IF Added -->
            <h3 class="names">Diyan Kalaydziev</h3>

            <!-- User Email Address -->
            <p class="email">d.denov@gmail.com</p>

            <!-- User Gender IF Added -->
            <p class="gender">Male</p>
          </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
          <div class="statuses">
            <!-- Start 1st Pet Details Page -->
            <!-- Link to First Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgoIHq82qLYnvomfz5ZkW5CLQ8VNxCyI-hUw&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Sasho</p>
              </div>
            </a>
            <!-- End 1st Pet Details Page -->

            <!-- Start 2nd Pet Details Page -->
            <!-- Link to Second Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313__340.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Todi</p>
              </div>
            </a>
            <!-- End 2nd Pet Details Page -->

            <!-- Start 3rd Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://images.unsplash.com/photo-1611003228941-98852ba62227?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFieSUyMGRvZ3xlbnwwfHwwfHw%3D&w=1000&q=80"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Mihail</p>
              </div>
            </a>
            <!-- End 3rd Pet Details Page -->

            <!-- Start 4th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Petar</p>
              </div>
            </a>
            <!-- End 4th Pet Details Page -->

            <!-- Start 5th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdKYe00NaD5SQjIMvXYPssq0r1dXJggL3ZIg&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Stamat</p>
              </div>
            </a>
            <!-- End 5th Pet Details Page -->

            <!-- Start 6th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Toni</p>
              </div>
            </a>
            <!-- End 6th Pet Details Page -->

            <!-- Start 7th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://i.pinimg.com/736x/01/6f/72/016f72c5812e1b8f71bdbf19d8c7558b.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Daisy</p>
              </div>
            </a>
            <!-- End 7th Pet Details Page -->
          </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">
          <!-- Link to Last Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://thumbs.dreamstime.com/b/small-golden-retriever-puppy-6482030.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to  Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.pinimg.com/originals/4e/55/83/4e5583748bc4000805df50e4ebcafffc.png"
              alt="pet img"
            />
          </a>
        </div>
        <!-- End Last Uploaded Photos Section -->

        <!-- IF NO Posts Show No Post Image -->

        <img
          class="no-posts"
          src="/static/images/no_posts.png"
          alt="no posts"
        />
      </div>

{% endblock %}

templates/accounts/profile-edit-page.html
{% extends 'shared/base.html' %}

{% block content %}

    <!-- Start Edit Profile Section -->
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form action="">
            <div class="label-input">
                <label for="first name">First name: </label>
                <input type="text" placeholder="First name" value="Diyan">
            </div>
            <br>
            <div class="label-input">
                <label for="last name">Last name: </label>
                <input type="text" placeholder="Last name" value="Kalayadzhiev">
            </div>
            <br>
            <div class="label-input">
                <label for="username">Username: </label>
                <input type="text" placeholder="Username" value="k_dido">
            </div>
            <br>
            <div class="label-input">
                <label for="email">Email: </label>
                <input type="email" placeholder="Email" value="d.denov@gmail.com">
            </div>
            <br>
            <div class="label-input">
                <label for="image">Image: </label>
                <input type="text" placeholder="Link to to profile picture"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">
            </div>
            <br>

            <div class="label-input">
                <label for="image">Gender: </label>
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        <label>
                            <input type="radio" name="gender"/> <span>Male</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Female</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Do not show</span>
                        </label>
                    </div>
                </div>
            </div>

            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->

    </div>
    <!-- End Edit Profile Section -->

{% endblock %}

templates/accounts/register-page.html
{% extends 'shared/base.html' %}

{% block content %}

    <!-- Start Register Section -->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form action="">
                <input type="text" placeholder="Username">

                <input type="email" placeholder="Email">

                <input type="password" placeholder="Password">

                <input type="password" placeholder="Repeat Password">

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="#">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section -->

{% endblock %}

templates/pets/pet-add-page.html
{% extends 'shared/base.html' %}

{% block content %}

    <!-- Start Add Pet Section-->
    <div class="edit-delete edit-photo">
        <h2>Add pet</h2>

        <!-- Start Add Pet Form -->
        <form action="#">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Pet name">
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date">
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image">
            </p>
            <!-- Add Pet Button -->
            <button class="add-btn" type="submit">Add Pet</button>
        </form>
        <!-- End Add Pet Form -->

    </div>
    <!-- End Add Pet Section -->

{% endblock %}

templates/pets/pet-delete-page.html
{% extends 'shared/base.html' %}

{% block content %}

    <!-- Starts Delete Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Delete pet</h2>
        <!-- Starts Delete Pet Form -->
        <form action="#">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Name" value="Sasho" disabled>
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date" disabled>
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                       alt="pet image" disabled>
            </p>
            <!-- Delete Pet Button -->
            <button class="delete-btn" type="submit">Delete</button>
            <!-- Go Back Button -->
            <a class="btn btn-primary" href="javascript:history.back()">
                <button class="edit-btn" type="button">Go back</button>
            </a>
        </form>
        <!-- End Delete Pet Form -->
    </div>
    <!-- End Delete Pet Section -->
{% endblock %}

templates/pets/pet-edit-page.html
{% extends 'shared/base.html' %}

{% block content %}

    <!-- Start Edit Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit Pet</h2>
        <!-- Start Edit Pet From -->
        <form action="">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Name" value="Sasho">
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date">
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                       alt="pet image">
            </p>
            <!-- Edit Pet Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Pet Form -->

    </div>
    <!-- End Edit Pet Section -->

{% endblock %}

templates/photos/photo-add-page.html
{% extends 'shared/base.html' %}

{% block content %}
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
{% endblock %}

templates/photos/photo-edit-page.html
{% extends 'shared/base.html' %}

{% block content %}


    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

{% endblock %}

templates/shared/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}">
    <title>Petstagram</title>
</head>

<body>

<header>
    {% include 'shared/nav.html' %}
</header>

<main>
    {% block content %}
    {% endblock %}
</main>

<div class="footer">
    {% include 'shared/footer.html' %}
</div>

</body>
</html>

templates/shared/footer.html
<span class="footer-section">
    ©  SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
</span>

templates/shared/nav.html
{% load static %}
<nav class="navbar">
    <div class="container">
        <div class="logo">
            <!-- Link to Home Page -->
            <a href="{% url 'common:home_page' %}">
                <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}" alt="img1">
            </a>

            <!-- Link to Home Page -->
            <a class="home" href="{% url 'common:home_page' %}">
                <i>Petstagram</i>
            </a>
        </div>

        <div class="nav-links">
            <ul class="nav-group">
                <li class="nav-item">

                    <!-- Link to Add Pet Page -->
                    <a href="{% url 'pets:pet-add' %}">
                        <i>Add Pet</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Link to Add Photo Page -->
                    <a href="{% url 'photos:add-photo' %}">
                        <i>Add Photo</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Link to Login Page -->
                    <a href="{% url 'accounts:login' %}">
                        <i>Login</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Link to Register Page -->
                    <a href="{% url 'accounts:register' %}">
                        <i>Register</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Link to Profile Page -->
                    <a href="">
                        <i>Profile</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Lpg out -->
                    <a href="#">
                        <i>Log out</i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>